export let TipsData = [
    { title: "En casa",text: "Apaga las luces que no estas usando", image: "assets/imgs/tips/Tips-05.png", index: 0 },
    { title: "En casa",text: "Desconecta el cargador cuando no lo estes usando", image: "assets/imgs/tips/Tips-03.png", index: 1 },
    { title: "En casa",text: "Bañate en menos de 7 minutos", image: "assets/imgs/tips/Tips-02.png", index: 2 },
    { title: "En casa",text: "Dona la ropa que no uses", image: "assets/imgs/tips/Tips-04.png", index: 3 },
    { title: "En casa",text: " Bañate con agua fria para ahorrar energia", image: "assets/imgs/tips/Tips-02.png", index: 4 },
    { title: "En casa",text: "Cambia tus bombillos incandescentes por ahorradores", image: "assets/imgs/tips/Tips-01.png", index: 5 },
    { title: "En casa",text: "Apaga las luces", image: "assets/imgs/tips/Tips-01.png", index: 6 },
    { title: "En casa",text: "Siembra plantas con flores para ayudar en la polinizacion", image: "assets/imgs/tips/Tips-08.png", index: 7 },
    { title: "En la calle",text: "Cuando manejas intenta no frenar en seco", image: "assets/imgs/tips/Tips-06.png", index: 8 },
    { title: "En la calle",text: "Usa el transporte publico", image: "assets/imgs/tips/Tips-11.png", index: 9 },
    { title: "En la calle",text: "Si vas a estar en un trancon por mucho tiempo, intenta apagar el carro", image: "assets/imgs/tips/Tips-06.png", index: 10 },
    { title: "En la calle",text: "Usa el transporte publico", image: "assets/imgs/tips/Tips-14.png", index: 11 },
    { title: "En la calle",text: "Revisa las rutas para evitar trancones", image: "assets/imgs/tips/Tips-06.png", index: 12 },
    { title: "En la calle",text: "No arrojes basura al piso", image: "assets/imgs/tips/Tips-10.png", index: 13 },
    { title: "En la calle",text: "Compra en almacenes que sean responsable con el medio ambiente", image: "assets/imgs/tips/Tips-13.png", index: 14 },
    { title: "En la calle",text: "Busca un punto de reciclaje para baterías y otros elementos electrónicos", image: "assets/imgs/tips/Tips-07.png", index: 15 },
    { title: "En la calle",text: "Lava tu carro en seco", image: "assets/imgs/tips/Tips-06.png", index: 16 },
    { title: "En la U",text: "Evita imprimit los documentos, probablemente  puedas leerlos en tu dispositivo movil", image: "assets/imgs/tips/Tips-09.png", index: 17 },
    { title: "En la U",text: "Termina tus cuadernos antes de comprar nuevos", image: "assets/imgs/tips/Tips-15.png", index: 18 },
    { title: "En la U",text: "Lleva el agua en termo en lugar de botellas", image: "assets/imgs/tips/Tips-16.png", index: 19 },
    { title: "En la U",text: "Pregunta a tus profesores si puedes entregar tus trabajos en papel reciclado", image: "assets/imgs/tips/Tips-12.png", index: 20 }
]